### ISSUE TITLE
Document using different deploy directories for different node/rails env

### ISSUE THREAD

**Issue by justin808** [shakacode/webpacker-lite#4]
We're often modifying our JS code for the different ENVs...

So if the directory for deployment is:

Production: /public/webpack
Development: /public/wepback/development
Test: /public/webpack/test

@robwise can comment more on this.

@kaizencodes This is instead of having the manifest have a different extension. Instead, it gets a different directory.

CC: @alexfedoseev

**Comment by kaizencodes** [comment]
If dev and test has it's own sub dir, why not production?

**Comment by robwise** [comment]
yeah I agree, why not keep the same pattern? This doesn't need to be inside of webpacker-lite though, you can just use a case statement to set your output dir conditionally on the env?

**Comment by kaizencodes** [comment]
Right. I tried it setting in the yml works just fine.

**Comment by justin808** [comment]
Thanks @kaizencodes and @robwise!  I'll close this when we have this documented.
